# Generated by Django 4.2.4 on 2023-09-19 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adminrole',
            fields=[
                ('roleID', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=45)),
                ('Lname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='trader',
            fields=[
                ('traderID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=45)),
                ('Lname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='traderlogin',
            fields=[
                ('traderLoginID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('traderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.trader')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=45)),
                ('QuantityAvailable', models.IntegerField()),
                ('priceOfEach', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('Description', models.CharField(max_length=2000)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.category')),
                ('traderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.trader')),
            ],
        ),
        migrations.CreateModel(
            name='customerlogin',
            fields=[
                ('customerLoginID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.customer')),
            ],
        ),
        migrations.CreateModel(
            name='checkoutbasket',
            fields=[
                ('basketID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=45)),
                ('Quantity', models.IntegerField()),
                ('paymentOption', models.CharField(max_length=45)),
                ('paid', models.BooleanField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.customer')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='admins',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=45)),
                ('Lname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('roleID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.adminrole')),
                ('uuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('adminLoginID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.admins')),
            ],
        ),
    ]
