# Generated by Django 4.2.4 on 2023-09-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='uuser',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='user',
        ),
    ]
